// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWKQE3covpD6DjPhxB2Pb3xav6igvN_TI',
    appId: '1:543318453097:android:daf07ff4d04053a861ebf8',
    messagingSenderId: '543318453097',
    projectId: 'chatapptute-c6c50',
    storageBucket: 'chatapptute-c6c50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ggtr_MrU-m21VEPLMdUEizxrokp7i3A',
    appId: '1:543318453097:ios:25ca7d00e432a67e61ebf8',
    messagingSenderId: '543318453097',
    projectId: 'chatapptute-c6c50',
    storageBucket: 'chatapptute-c6c50.firebasestorage.app',
    iosBundleId: 'com.abdullox.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ggtr_MrU-m21VEPLMdUEizxrokp7i3A',
    appId: '1:543318453097:ios:25ca7d00e432a67e61ebf8',
    messagingSenderId: '543318453097',
    projectId: 'chatapptute-c6c50',
    storageBucket: 'chatapptute-c6c50.firebasestorage.app',
    iosBundleId: 'com.abdullox.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgKXm3egXzrmr4jQvXrrM4CeOeoFIYrsg',
    appId: '1:543318453097:web:634d4a08fc61ac7261ebf8',
    messagingSenderId: '543318453097',
    projectId: 'chatapptute-c6c50',
    authDomain: 'chatapptute-c6c50.firebaseapp.com',
    storageBucket: 'chatapptute-c6c50.firebasestorage.app',
  );
}
